In [3]:
# 基于Surprise框架的推荐系统Demo
from surprise import KNNBasic
from surprise import Dataset
from surprise import evaluate, print_perf

# http://surprise.readthedocs.io/en/stable/index.html
# http://files.grouplens.org/datasets/movielens/ml-100k-README.txt

# Load the movielens-100k dataset (download it if needed),
# and split it into 3 folds for cross-validation.
data = Dataset.load_builtin('ml-100k')
data.split(n_folds=3)
# We'll use the famous KNNBasic algorithm.
knn = KNNBasic()
# Evaluate performances of our algorithm on the dataset.
perf = evaluate(knn, data, measures=['RMSE', 'MAE'])
print_perf(perf)

/Users/wugang/env/anaconda3/python.app/Contents/lib/python3.5/site-packages/scikit_surprise-1.0.6-py3.5-macosx-10.6-x86_64.egg/surprise/evaluate.py:66: UserWarning: The evaluate() method is deprecated. Please use model_selection.cross_validate() instead.
  'model_selection.cross_validate() instead.', UserWarning)
/Users/wugang/env/anaconda3/python.app/Contents/lib/python3.5/site-packages/scikit_surprise-1.0.6-py3.5-macosx-10.6-x86_64.egg/surprise/dataset.py:220: UserWarning: Using data.split() or using load_from_folds() without using a CV iterator is now deprecated.
  UserWarning)

Evaluating RMSE, MAE of algorithm KNNBasic.

------------
Fold 1
Computing the msd similarity matrix...
Done computing similarity matrix.

RMSE: 0.9889
MAE:  0.7803
------------
Fold 2
Computing the msd similarity matrix...

Done computing similarity matrix.

RMSE: 0.9908
MAE:  0.7832
------------
Fold 3

Computing the msd similarity matrix...
Done computing similarity matrix.

RMSE: 0.9878
MAE:  0.7816
------------
------------
Mean RMSE: 0.9892
Mean MAE : 0.7817
------------
------------
        Fold 1  Fold 2  Fold 3  Mean
MAE     0.7803  0.7832  0.7816  0.7817
RMSE    0.9889  0.9908  0.9878  0.9892

In [5]:
from surprise import SVD
from surprise.model_selection import GridSearchCV

# 所需参数候选值：epoch、学习率和正则化参数
# 共组合2*2*2=8种参数组合
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
gs = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3)
gs.fit(data)

# best RMSE score
print(gs.best_score['rmse'])
# combination of parameters that gave the best RMSE score
print(gs.best_params['rmse'])

# 将各个参数组合的结果列表展示
import pandas as pd

results_df = pd.DataFrame.from_dict(gs.cv_results)
results_df

0.9635950266798726
{'lr_all': 0.005, 'n_epochs': 10, 'reg_all': 0.4}

/Users/wugang/env/anaconda3/python.app/Contents/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

/Users/wugang/env/anaconda3/python.app/Contents/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>mean_fit_time</th>
      <th>mean_test_mae</th>
      <th>mean_test_rmse</th>
      <th>mean_test_time</th>
      <th>param_lr_all</th>
      <th>param_n_epochs</th>
      <th>param_reg_all</th>
      <th>params</th>
      <th>rank_test_mae</th>
      <th>rank_test_rmse</th>
      <th>split0_test_mae</th>
      <th>split0_test_rmse</th>
      <th>split1_test_mae</th>
      <th>split1_test_rmse</th>
      <th>split2_test_mae</th>
      <th>split2_test_rmse</th>
      <th>std_fit_time</th>
      <th>std_test_mae</th>
      <th>std_test_rmse</th>
      <th>std_test_time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.998560</td>
      <td>0.806102</td>
      <td>0.997322</td>
      <td>0.315428</td>
      <td>0.002</td>
      <td>5</td>
      <td>0.4</td>
      <td>{'lr_all': 0.002, 'n_epochs': 5, 'reg_all': 0.4}</td>
      <td>7</td>
      <td>7</td>
      <td>0.796968</td>
      <td>0.988911</td>
      <td>0.810063</td>
      <td>1.002999</td>
      <td>0.811276</td>
      <td>1.000056</td>
      <td>0.036593</td>
      <td>0.006478</td>
      <td>0.006067</td>
      <td>0.061769</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.947777</td>
      <td>0.814693</td>
      <td>1.003356</td>
      <td>0.301667</td>
      <td>0.002</td>
      <td>5</td>
      <td>0.6</td>
      <td>{'lr_all': 0.002, 'n_epochs': 5, 'reg_all': 0.6}</td>
      <td>8</td>
      <td>8</td>
      <td>0.805437</td>
      <td>0.994681</td>
      <td>0.818581</td>
      <td>1.009099</td>
      <td>0.820061</td>
      <td>1.006288</td>
      <td>0.016386</td>
      <td>0.006573</td>
      <td>0.006240</td>
      <td>0.050943</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2.018068</td>
      <td>0.785961</td>
      <td>0.977996</td>
      <td>0.308900</td>
      <td>0.002</td>
      <td>10</td>
      <td>0.4</td>
      <td>{'lr_all': 0.002, 'n_epochs': 10, 'reg_all': 0.4}</td>
      <td>4</td>
      <td>4</td>
      <td>0.776766</td>
      <td>0.969648</td>
      <td>0.789723</td>
      <td>0.983718</td>
      <td>0.791393</td>
      <td>0.980622</td>
      <td>0.158187</td>
      <td>0.006537</td>
      <td>0.006037</td>
      <td>0.004565</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.876242</td>
      <td>0.796476</td>
      <td>0.986164</td>
      <td>0.277767</td>
      <td>0.002</td>
      <td>10</td>
      <td>0.6</td>
      <td>{'lr_all': 0.002, 'n_epochs': 10, 'reg_all': 0.6}</td>
      <td>6</td>
      <td>6</td>
      <td>0.787202</td>
      <td>0.977569</td>
      <td>0.800398</td>
      <td>0.992143</td>
      <td>0.801829</td>
      <td>0.988781</td>
      <td>0.036667</td>
      <td>0.006584</td>
      <td>0.006231</td>
      <td>0.026832</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1.052878</td>
      <td>0.781780</td>
      <td>0.973620</td>
      <td>0.318643</td>
      <td>0.005</td>
      <td>5</td>
      <td>0.4</td>
      <td>{'lr_all': 0.005, 'n_epochs': 5, 'reg_all': 0.4}</td>
      <td>2</td>
      <td>3</td>
      <td>0.773064</td>
      <td>0.965483</td>
      <td>0.785179</td>
      <td>0.979327</td>
      <td>0.787096</td>
      <td>0.976052</td>
      <td>0.151448</td>
      <td>0.006212</td>
      <td>0.005908</td>
      <td>0.064252</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.984598</td>
      <td>0.792693</td>
      <td>0.982333</td>
      <td>0.289444</td>
      <td>0.005</td>
      <td>5</td>
      <td>0.6</td>
      <td>{'lr_all': 0.005, 'n_epochs': 5, 'reg_all': 0.6}</td>
      <td>5</td>
      <td>5</td>
      <td>0.783820</td>
      <td>0.973903</td>
      <td>0.796388</td>
      <td>0.988327</td>
      <td>0.797871</td>
      <td>0.984769</td>
      <td>0.007856</td>
      <td>0.006303</td>
      <td>0.006135</td>
      <td>0.034606</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2.050858</td>
      <td>0.772350</td>
      <td>0.963595</td>
      <td>0.292109</td>
      <td>0.005</td>
      <td>10</td>
      <td>0.4</td>
      <td>{'lr_all': 0.005, 'n_epochs': 10, 'reg_all': 0.4}</td>
      <td>1</td>
      <td>1</td>
      <td>0.764088</td>
      <td>0.955937</td>
      <td>0.775624</td>
      <td>0.969407</td>
      <td>0.777338</td>
      <td>0.965441</td>
      <td>0.153612</td>
      <td>0.005884</td>
      <td>0.005652</td>
      <td>0.045053</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1.902498</td>
      <td>0.784173</td>
      <td>0.973518</td>
      <td>0.275965</td>
      <td>0.005</td>
      <td>10</td>
      <td>0.6</td>
      <td>{'lr_all': 0.005, 'n_epochs': 10, 'reg_all': 0.6}</td>
      <td>3</td>
      <td>2</td>
      <td>0.775739</td>
      <td>0.965547</td>
      <td>0.787623</td>
      <td>0.979470</td>
      <td>0.789156</td>
      <td>0.975536</td>
      <td>0.026279</td>
      <td>0.005996</td>
      <td>0.005860</td>
      <td>0.033275</td>
    </tr>
  </tbody>
</table>
</div>

In [8]:
def read_item_names():
    """
    将电影名字和ID进行映射
    :return:
    """
    import io

    file_name = ('/Users/wugang/code/python/rec-demo/data/ml-100k/u.item')
    rid_to_name = {}
    name_to_rid = {}
    with io.open(file_name, 'r', encoding='ISO-8859-1') as f:
        for line in f:
            line = line.split('|')
            rid_to_name[line[0]] = line[1]
            name_to_rid[line[1]] = line[0]
    return rid_to_name, name_to_rid

# test read_item_names
rid_to_name, name_to_rid = read_item_names()
toy_story_raw_id = name_to_rid['Now and Then (1995)']
print(toy_story_raw_id)
raw_id_toy_story = rid_to_name['1053']
print(raw_id_toy_story)

1053
Now and Then (1995)

In [10]:

# 推荐Demo
train_data = data.build_full_trainset()
# 皮尔逊系数计算相似度，基于物品的推荐
sim_options = {'name': 'pearson_baseline', 'user_based': False}
from surprise import KNNBaseline

knn = KNNBaseline(sim_options=sim_options)
knn.fit(train_data)

rid_to_name, name_to_rid = read_item_names()
toy_story_raw_id = name_to_rid['Now and Then (1995)']
print("数据中的ID：%s" % toy_story_raw_id)

# toy_story_inner_id在实际要计算的矩阵中的ID。
toy_story_inner_id = knn.trainset.to_inner_iid(toy_story_raw_id)
print("矩阵中的ID：%s" % toy_story_inner_id)
toy_story_neighbors = knn.get_neighbors(toy_story_inner_id, k=10)
print("最近邻：%s" % toy_story_neighbors)

# 对近邻集合中对ID进行转换为名字
toy_story_neighbors = (knn.trainset.to_raw_iid(inner_id)
                       for inner_id in toy_story_neighbors)
toy_story_neighbors = (rid_to_name[rid]
                       for rid in toy_story_neighbors)
print()
print('推荐的Top 10 :')
for movie in toy_story_neighbors:
    print(movie)

Estimating biases using als...

Computing the pearson_baseline similarity matrix...

Done computing similarity matrix.
数据中的ID：1053
矩阵中的ID：564
最近邻：[518, 425, 90, 386, 476, 52, 569, 327, 291, 333]

推荐的Top 10 :
While You Were Sleeping (1995)
Batman (1989)
Dave (1993)
Mrs. Doubtfire (1993)
Groundhog Day (1993)
Raiders of the Lost Ark (1981)
Maverick (1994)
French Kiss (1995)
Stand by Me (1986)
Net, The (1995)